planning_plugins:
  - ompl_interface/OMPLPlanner
planning_plugin: ompl_interface/OMPLPlanner

ompl:
  planning:
    lite6:
      default_planner_config: RRTConnect
      planner_configs:
        - SBL
        - EST
        - LBKPIECE
        - BKPIECE
        - KPIECE
        - RRT
        - RRTConnect
        - RRTstar
        - TRRT
        - PRM
        - PRMstar
        - FMT
        - BFMT
        - PDST
        - STRIDE
        - BiTRRT
        - LBTRRT
        - BiEST
        - ProjEST
        - LazyPRM
        - LazyPRMstar
        - SPARS
        - SPARStwo
    