# Goal request (De aanvraag)
string object_type
geometry_msgs/Point position
geometry_msgs/Quaternion rotation

---
# Result response (Het eindresultaat)
bool success
string message

---
# Feedback (Tussentijdse updates tijdens de beweging)
string current_state
